Repository BEST-L2CP/ChickMate, pull requests merged in 2025-04, with the labels that each got.

#13 Prisma Schema 수정
  prisma/schema.prisma
  src/app/api/auth/sign-in/route.ts
  src/utils/auth-option.ts
Labels: 🐞 BugFix, 🕶️ 재원, 🚨 ASAP, 🗄️ db

#12 Bugfix/#11-tailwind-config-수정
  public/fonts/SUIT-Variable.woff2
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🐞 BugFix, ⚙ Setting, 💎다혜

#14 Reafactor/#8 sign
  src/app/api/auth/sign-in/route.ts
  src/app/api/sign-up/route.ts
  src/app/sign-in/page.tsx
  src/components/common/auth-form.tsx
  src/constants/path-constant.ts
  src/features/sign-up/api/client-services.ts
  src/utils/auth-option.ts
Labels: 🔨 Refactor, 🕶️ 재원, 🚨 ASAP

#20 Feature/#9 main page nav
  src/app/(with-nav)/layout.tsx
  src/app/(with-nav)/my-page/page.tsx
  src/app/(with-nav)/on-boarding/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/constants/path-constant.ts
  src/features/layout/button-nav.tsx
  src/features/layout/data/nav-items.ts
  src/features/layout/header.tsx
  src/features/layout/link-nav.tsx
  src/features/layout/nav.tsx
  src/middleware.ts
Labels: 🥰 Accessibility, ✨ Feature, D-1, 💎다혜

#26 Feature/#9 main page
  src/app/(with-nav)/layout.tsx
  src/app/(with-nav)/my-page/page.tsx
  src/app/(with-nav)/on-boarding/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/constants/path-constant.ts
  src/features/layout/button-nav.tsx
  src/features/layout/data/nav-items.ts
  src/features/layout/header.tsx
  src/features/layout/link-nav.tsx
  src/features/layout/nav.tsx
  src/middleware.ts
Labels: 🥰 Accessibility, ✨ Feature, 💎다혜

#23 Feature/#17 sign up validation
  package.json
  pnpm-lock.yaml
  src/app/api/sign-up/route.ts
  src/app/auth/sign-in/page.tsx
  src/app/auth/sign-up/character/page.tsx
  src/app/auth/sign-up/page.tsx
  src/app/sign-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/common/auth-form.tsx
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/auth/auth-input.tsx
  src/features/auth/sign-up/api/client-services.ts
  src/features/auth/sign-up/data/schema.ts
  src/features/auth/sign-up/sign-up-auth-form.tsx
  src/features/auth/sing-in/sign-in-auth-form.tsx
  src/features/layout/data/nav-items.ts
Labels: ✨ Feature, 🔨 Refactor, 🕶️ 재원, D-1

#30 Featuer/#29 sign in validation
  public/assets/google_icon.png
  public/assets/naver_icon.png
  src/constants/message-constants.ts
  src/features/auth/auth-input.tsx
  src/features/auth/sign-up/api/client-services.ts
  src/features/auth/sign-up/data/schema.ts
  src/features/auth/sign-up/sign-up-auth-form.tsx
  src/features/auth/sing-in/data/schema.ts
  src/features/auth/sing-in/sign-in-auth-form.tsx
Labels: ✨ Feature, 🔨 Refactor, 🕶️ 재원, D-1

#32 Feature/#28 webcam preview
  package.json
  src/app/(interview)/interview-live/page.tsx
  src/app/(interview)/interview-start/page.tsx
  src/features/interview/camera-view.tsx
  src/features/interview/hooks/use-audio-recorder.ts
  src/features/interview/hooks/use-webcam-stream.ts
  src/features/interview/voice-input-button.tsx
Labels: ✨ Feature, D-1, ☕️민조

#35 Chore/pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#37 Feature/#33 sentry
  .github/workflows/CI_Build_test.yml
  .gitignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sign-up/route.ts
  src/app/auth/sign-in/page.tsx
  src/app/global-error.tsx
  src/constants/env-constants.ts
  src/features/auth/sign-in/data/schema.ts
  src/features/auth/sign-in/sign-in-auth-form.tsx
  src/features/auth/sign-up/api/client-services.ts
  src/instrumentation-client.ts
  src/instrumentation.ts
  src/utils/fetch-with-sentry.ts
  src/utils/server-action-with-sentry.ts
Labels: ✨ Feature, 🕶️ 재원, D-1

#36 Feature/#18 음성 면접 기능 stt
  .github/workflows/CI_Build_test.yml
  src/app/api/ ai/route.ts
  src/app/api/ai/stt/route.ts
  src/app/api/ai/tts/route.ts
  src/constants/api-method-constants.ts
  src/constants/env-constants.ts
  src/constants/interview-constants.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/interview/api/client-services.ts
  src/features/interview/stt-component.tsx
  src/features/interview/tts-component.tsx
  src/features/interview/voice-input-button.tsx
  src/instrumentation-client.ts
Labels: ✨ Feature, D-1, ♟️창연

#38 Style/#31 text common component
  package.json
  pnpm-lock.yaml
  src/components/ui/text.tsx
  src/components/ui/title.tsx
  src/styles/typography-styles.ts
Labels: 🎨 Styles, D-1, ☕️민조

#39 Feature/#7 open ai api 연결
  src/app/(interview)/interview-live/page.tsx
  src/app/api/ai/interview/route.ts
  src/constants/interview-constants.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/interview/api/client-services.ts
  src/features/interview/interview-component.tsx
  src/types/message.ts
Labels: ✨ Feature, 🚨 ASAP, ♟️창연

#43 db schema update
  prisma/schema.prisma
  src/app/api/sample/[id]/route.ts
Labels: 🕶️ 재원, 🚨 ASAP, 🗄️ db

#50 Refactor/#49 password confirm
  src/app/auth/sign-in/page.tsx
  src/app/auth/sign-up/page.tsx
  src/constants/message-constants.ts
  src/features/auth/sign-up/data/schema.ts
  src/features/sign/api/client-services.ts
  src/features/sign/auth-input.tsx
  src/features/sign/data/sign-in-schema.ts
  src/features/sign/data/sign-up-schema.ts
  src/features/sign/sign-in-auth-form.tsx
  src/features/sign/sign-up-auth-form.tsx
Labels: ✨ Feature, 🔨 Refactor, 🕶️ 재원, D-2

#48 db schema update
  prisma/schema.prisma
Labels: 🕶️ 재원, 🚨 ASAP, 🗄️ db

#53 Feature/#52 session
  src/hooks/customs/use-user-session.ts
  src/types/user.ts
Labels: ✨ Feature, 🚨 ASAP

#57 Feature/#27 user meta data
  src/app/(with-nav)/my-page/page.tsx
  src/app/api/regions/route.ts
  src/app/api/user-meta-data/[userId]/route.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/constants/time.ts
  src/constants/user-meta-data-constants.ts
  src/features/user-meta-data/api/client-services.ts
  src/features/user-meta-data/api/server-services.ts
  src/features/user-meta-data/data/user-meta-data.ts
  src/features/user-meta-data/data/user-meta-form-schema.ts
  src/features/user-meta-data/hooks/use-meta-data-mutation.ts
  src/features/user-meta-data/hooks/use-regions-query.ts
  src/features/user-meta-data/select-box.tsx
  src/features/user-meta-data/single-select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
  src/types/select-box.ts
  src/types/user-meta-data-type.ts
  src/utils/server-action-with-sentry.ts
Labels: ✨ Feature, D-2, 💎다혜

#55 Feature/#41 personal statement write
  src/app/(with-nav)/resume/[id]/page.tsx
  src/app/(with-nav)/resume/page.tsx
  src/app/api/resume/draft/.gitkeep
  src/app/api/resume/submit/route.ts
  src/app/api/sample/[id]/route.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/resume-constants.ts
  src/features/layout/data/nav-items.ts
  src/features/resume/api/client-service.ts
  src/features/resume/data/default-question-list.ts
  src/features/resume/hooks/use-prevent-page-load.ts
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form.tsx
  src/features/resume/user-info-summary.tsx
  src/middleware.ts
  src/types/resume.ts
  src/types/route-params.ts
Labels: 📬 API, ✨ Feature, D-1, ☕️민조

#46 Feature/#40 채용정보 api
  src/app/api/job/posting/route.ts
  src/app/job/page.tsx
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/job/api/client-services.ts
  src/features/job/job-posting-card.tsx
Labels: 📬 API, ✨ Feature, D-1, ♟️창연

#61 Feature/#47 chracter exp
  public/assets/character/header/level1.jpeg
  public/assets/character/header/level2.jpeg
  public/assets/character/header/level3.jpeg
  public/assets/character/header/level4.jpeg
  src/app/(with-nav)/(with-header)/character/page.tsx
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/(with-nav)/layout.tsx
  src/app/api/auth/sign-in/route.ts
  src/app/api/character/experience/route.ts
  src/app/api/character/reset/route.ts
  src/app/api/character/route.ts
  src/app/auth/sign-in/page.tsx
  src/app/auth/sign-up/page.tsx
  src/constants/api-method-constants.ts
  src/constants/character-constants.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/chraracter/api/client-services.ts
  src/features/chraracter/api/server-services.ts
  src/features/chraracter/header-character.tsx
  src/features/chraracter/hooks/use-get-character-query.ts
  src/features/chraracter/utils/get-level-and-percent.ts
  src/features/layout/header.tsx
  src/features/layout/nav.tsx
  src/features/sign/ hooks/use-sign-in-result.ts
  src/features/sign/auth-input.tsx
  src/features/sign/sign-in-auth-form.tsx
  src/features/sign/sign-up-auth-form.tsx
  src/hooks/mutations/use-post-experience-mutation.ts
  src/middleware.ts
  src/store/use-character-store.ts
  src/utils/auth-option.ts
Labels: ✨ Feature, 🕶️ 재원, D-2

#60 Feature/#51 채용정보 북마크 api
  src/app/api/job/bookmark/[id]/route.ts
  src/app/api/job/posting/route.ts
  src/app/job/page.tsx
  src/components/common/.gitkeep
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/job/api/client-services.ts
  src/features/job/bookmark-component.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/hooks/use-bookmark-query.ts
Labels: 📬 API, ✨ Feature, D-1, ♟️창연

#67 Feature/#54 middleware token
  src/app/api/user-meta-data/[userId]/route.ts
  src/components/common/error-component.tsx
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/interview/api/client-services.ts
  src/features/layout/button-nav.tsx
  src/features/layout/header.tsx
  src/features/layout/link-nav.tsx
  src/features/layout/nav.tsx
  src/features/resume/api/client-services.ts
  src/features/sign/hooks/use-sign-in-result.ts
  src/features/sign/sign-in-auth-form.tsx
  src/features/user-meta-data/api/client-services.ts
  src/features/user-meta-data/api/server-services.ts
  src/features/user-meta-data/hooks/use-meta-data-mutation.ts
  src/features/user-meta-data/hooks/use-regions-query.ts
  src/features/user-meta-data/single-select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
  src/hooks/customs/use-user-session.ts
  src/middleware.ts
  src/types/select-box.ts
  src/utils/auth-option.ts
  src/utils/fetch-with-sentry.ts
  tsconfig.json
Labels: 🥰 Accessibility, ✨ Feature, 🔨 Refactor, D-1, 💎다혜

#68 Feature/#64 modal component
  src/app/api/resume/[id]/route.ts
  src/app/api/resume/draft/[id]/route.ts
  src/app/api/resume/route.ts
  src/components/ui/modal.tsx
  src/components/ui/text.tsx
  src/components/ui/title.tsx
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/resume-constants.ts
  src/features/.gitkeep
  src/features/resume/api/client-services.ts
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/hooks/use-delete-resume-mutation.ts
  src/features/resume/hooks/use-draft-resumes-query.ts
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/resume-form.tsx
  src/hooks/customs/use-modal.ts
  src/hooks/mutations/.gitkeep
  src/store/.gitkeep
  src/styles/typography-styles.ts
Labels: 📬 API, ✨ Feature, 🎨 Styles, D-1, ☕️민조

#71 Feature/#69 유틸 함수
  src/app/api/job/posting/route.ts
  src/utils/sanitize-query-params.ts
  tsconfig.json
Labels: 🚨 ASAP, ♟️창연

#77 bugfix:#76 임시 저장된 자소서 삭제한 뒤, DB 통신 안 되는 오류 해결
  src/components/common/modal.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/resume-form.tsx
Labels: 🐞 BugFix, ☕️민조

#79 Bugfix/#78 text component
  package.json
  pnpm-lock.yaml
  src/components/common/error-component.tsx
  src/components/common/modal.tsx
  src/components/ui/text.tsx
  src/components/ui/title.tsx
  src/components/ui/typography.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form.tsx
  src/styles/.gitkeep
  src/styles/typography-styles.ts
  tailwind.config.ts
Labels: 🐞 BugFix, 🎨 Styles, ☕️민조

#82 Feature/#63 create character
  .gitignore
  .vscode/settings.json
  next.config.mjs
  prisma/schema.prisma
  public/assets/character/card/yellow-level1.png
  public/assets/character/card/yellow-level2.png
  public/assets/character/card/yellow-level3.png
  public/assets/character/card/yellow-level4.png
  public/assets/character/header/level1.jpeg
  public/assets/character/header/level2.jpeg
  src/app/(with-nav)/(with-header)/(interview)/interview-live/page.tsx
  src/app/(with-nav)/(with-header)/(interview)/interview-start/page.tsx
  src/app/(with-nav)/(with-header)/my-page/page.tsx
  src/app/(with-nav)/(with-header)/resume/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/app/(with-nav)/layout.tsx
  src/app/(with-nav)/on-boarding/page.tsx
  src/app/api/character/route.ts
  src/constants/character-constants.ts
  src/constants/message-constants.ts
  src/features/character/api/client-services.ts
  src/features/character/api/server-services.ts
  src/features/character/character-exp-bar.tsx
  src/features/character/create-character-modal.tsx
  src/features/character/data/character-data.ts
  src/features/character/header-character.tsx
  src/features/character/hooks/use-character-store-sync.ts
  src/features/character/hooks/use-get-character-query.ts
  src/features/character/main-character-card.tsx
  src/features/character/main-character.tsx
  src/features/character/utils/get-level-and-percent.ts
  src/features/chraracter/api/client-services.ts
  src/features/chraracter/utils/get-level-and-percent.ts
  src/features/layout/header.tsx
  src/store/use-character-store.ts
  tailwind.config.ts
Labels: ✨ Feature, 🕶️ 재원, 🚨 ASAP

#74 Feature/#69 card component
  src/app/job/page.tsx
  src/components/common/job-posting-card.tsx
  src/components/common/resume-card.tsx
  src/components/ui/card.tsx
  src/components/ui/typography.tsx
  src/features/job/hooks/use-job-posting-query.ts
  src/features/job/job-posting-card.tsx
  src/utils/format-date.ts
  tailwind.config.ts
Labels: 🎨 Styles, ♟️창연

#81 fix:#80 meta data db에 맞춰 수정 및 전송 값 value -> name으로 변경
  src/features/user-meta-data/data/user-meta-data.ts
  src/features/user-meta-data/select-box.tsx
Labels: 🐞 BugFix, 🚨 ASAP, 💎다혜

#84 Feature/#70 common button
  setting.json
  src/app/page.tsx
  src/components/ui/button.tsx
  src/styles/button-styles.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Styles, 💎다혜

#88 Feature/#87 meta modal form refactor
  src/app/(with-nav)/(with-header)/my-page/page.tsx
  src/app/(with-nav)/layout.tsx
  src/app/api/user-meta-data/[userId]/route.ts
  src/components/common/error-component.tsx
  src/constants/message-constants.ts
  src/features/my-page/tabs-field.tsx
  src/features/my-page/viewing-field.tsx
  src/features/user-meta-data/api/client-services.ts
  src/features/user-meta-data/api/server-services.ts
  src/features/user-meta-data/data/user-meta-data.ts
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/features/user-meta-data/hooks/use-meta-data-mutation.ts
  src/features/user-meta-data/hooks/use-meta-data-query.ts
  src/features/user-meta-data/hooks/use-regions-query.ts
  src/features/user-meta-data/single-select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
Labels: 🔨 Refactor, 💎다혜

#89 Bugfix/#86 modal component
  src/components/ui/modal.tsx
  src/components/ui/typography.tsx
  src/constants/modal-id-constants.ts
  src/features/character/create-character-modal.tsx
  src/features/character/main-character-card.tsx
  src/features/my-page/viewing-field.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/resume-form.tsx
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/store/use-modal-store.ts
Labels: 🐞 BugFix, 🚨 ASAP, ☕️민조

#91 Feature/#90 nav layout fix
  src/app/(with-nav)/on-boarding/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/icons/file-dock-fill.tsx
  src/features/layout/data/nav-items.tsx
  src/features/layout/nav.tsx
Labels: 🎨 Styles, 🚨 ASAP, 💎다혜

#92 Feature/#42 ai interview
  src/app/(with-nav)/(with-header)/(interview)/interview-live/page.tsx
  src/app/api/ai/stt/route.ts
  src/app/api/resume/route.ts
  src/features/interview/api/client-services.ts
  src/features/interview/camera-view.tsx
  src/features/interview/hooks/use-audio-recorder.ts
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/interview/hooks/use-timer.ts
  src/features/interview/timer.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/store/use-modal-store.ts
Labels: 📬 API, ✨ Feature, 🚨 ASAP, ☕️민조

#94 Refactor/#83 캐릭터
  prisma/schema.prisma
  src/app/(with-nav)/(with-header)/character/page.tsx
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/(with-nav)/layout.tsx
  src/app/api/character/experience/route.ts
  src/app/api/character/route.ts
  src/components/ui/screen-overlay.tsx
  src/components/ui/typography.tsx
  src/constants/character-constants.ts
  src/constants/message-constants.ts
  src/constants/modal-id-constants.ts
  src/constants/path-constant.ts
  src/features/character/api/client-services.ts
  src/features/character/api/server-services.ts
  src/features/character/character-detail-modal.tsx
  src/features/character/character-exp-bar.tsx
  src/features/character/character-history.tsx
  src/features/character/create-character-modal.tsx
  src/features/character/header-character-card.tsx
  src/features/character/header-character.tsx
  src/features/character/hooks/use-character-card.ts
  src/features/character/hooks/use-experience-up.ts
  src/features/character/hooks/use-post-experience-mutation.ts
  src/features/character/main-character-card.tsx
  src/features/character/main-character.tsx
  src/features/character/my-character.tsx
  src/features/character/utils/get-level-and-percent.ts
  src/features/layout/header-title.tsx
  src/features/layout/header.tsx
  src/features/layout/utils/getTitleFromPath.ts
  src/features/sign/api/client-services.ts
  src/features/sign/hooks/use-sign-in-result.ts
  src/hooks/mutations/use-post-experience-mutation.ts
  src/middleware.ts
Labels: ✨ Feature, 🔨 Refactor, 🕶️ 재원

#98 Refactor/#96 button component refactoring
  src/components/ui/button.tsx
  src/styles/button-styles.ts
Labels: 🔨 Refactor, 🎨 Styles, 💎다혜

#100 Feature/#95 character history pagination
  prisma/schema.prisma
  src/app/api/character/history/[id]/route.ts
  src/app/api/character/reset/route.ts
  src/app/api/character/route.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/character/api/client-services.ts
  src/features/character/api/server-services.ts
  src/features/character/character-history.tsx
  src/features/character/hooks/use-character-history-infinite-query.ts
  src/features/character/hooks/use-post-experience-mutation.ts
  src/features/character/my-character.tsx
  src/hooks/customs/use-infinite-scroll.ts
Labels: ✨ Feature, 🕶️ 재원

#97 Refactor/#75 채용공고 페이지
  src/app/(with-nav)/(with-header)/interview/start/page.tsx
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/(with-nav)/layout.tsx
  src/app/api/job/posting/route.ts
  src/components/common/job-posting-card.tsx
  src/constants/query-key.ts
  src/constants/time-constants.ts
  src/features/job/api/client-services.ts
  src/features/job/api/server-services.ts
  src/features/job/bookmark-component.tsx
  src/features/job/bookmark.tsx
  src/features/job/hooks/use-job-posting-query.ts
  src/features/job/job-postings-box.tsx
  src/features/layout/data/nav-items.tsx
  src/features/user-meta-data/api/client-services.ts
  src/features/user-meta-data/api/server-services.ts
  src/utils/format-remain-day.ts
Labels: 🔨 Refactor, 🎨 Styles, 🚨 ASAP, ♟️창연

#101 Style/#99 main page UI
  public/assets/background.png
  public/assets/sub_background.png
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/(with-nav)/layout.tsx
  src/app/(with-nav)/on-boarding/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/icons/chat-alt-2-fill.tsx
  src/components/icons/file-dock-fill.tsx
  src/components/icons/file-dock-search-fill.tsx
  src/features/character/main-character-card.tsx
  src/features/layout/data/nav-items.tsx
  src/features/on-boarding/data/on-boarding-list.tsx
  src/features/on-boarding/list-card.tsx
  src/middleware.ts
Labels: 🔨 Refactor, 🎨 Styles, 💎다혜

#103 design:#96 색상 적용 오류 수정
  src/app/global-style.css
  src/styles/button-styles.ts
Labels: 🐞 BugFix, 🎨 Styles, 💎다혜

#108 BugFix
  src/app/api/job/posting/route.ts
  src/types/job-posting.ts
Labels: 🐞 BugFix, 🚨 ASAP

#110 Feature/#42 ai interview
  src/app/(with-nav)/(with-header)/(interview)/interview-live/page.tsx
  src/app/(with-nav)/(with-header)/interview/live/[id]/page.tsx
  src/app/api/ai/interview/[id]/route.ts
  src/app/api/ai/interview/route.ts
  src/app/api/ai/tts/route.ts
  src/constants/character-constants.ts
  src/constants/interview-constants.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/interview/api/client-services.ts
  src/features/interview/api/server-services.ts
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/interview/interview-component.tsx
  src/features/interview/question-display-with-timer.tsx
  src/features/interview/question-display.tsx
  src/features/interview/stt-component.tsx
  src/features/interview/timer.tsx
  src/features/interview/tts-component.tsx
  src/features/interview/voice-input-button.tsx
  src/features/resume/api/server-services.ts
  src/types/interview.ts
  src/types/message.ts
Labels: 📬 API, ✨ Feature, 🕶️ 재원, 🚨 ASAP, ☕️민조

#113 Style/#111 resume
  src/app/(with-nav)/(with-header)/resume/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/components/icons/interview-icon.tsx
  src/components/icons/job-icon.tsx
  src/components/icons/logout-icon.tsx
  src/components/icons/my-page-icon.tsx
  src/components/icons/resume-icon.tsx
  src/components/icons/sign-in-icon.tsx
  src/components/icons/sign-up-icon.tsx
  src/components/icons/trash.tsx
  src/features/layout/button-nav.tsx
  src/features/layout/data/nav-items.tsx
  src/features/layout/link-nav.tsx
  src/features/layout/nav.tsx
  src/features/resume/api/server-services.ts
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form.tsx
  src/features/resume/user-data-item.tsx
  src/features/resume/user-info-summary.tsx
  tailwind.config.ts
Labels: 🎨 Styles, ☕️민조

#115 Feature/#85 interview history list
  src/app/(with-nav)/(with-header)/my-page/page.tsx
  src/app/api/interview-history/[userId]/route.ts
  src/constants/interview-constants.ts
  src/constants/message-constants.ts
  src/constants/my-page-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/interview-history/api/client-services.ts
  src/features/interview-history/empty-interview-list.tsx
  src/features/interview-history/hook/use-interview-history-infinite-query.ts
  src/features/interview-history/interview-history-list.tsx
  src/features/my-page/list-by-tab.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/store/use-tab-store.ts
  src/types/tab-type.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Styles, 💎다혜

#120 Style/#112 ai interview live
  src/app/(with-nav)/(with-header)/interview/live/[id]/page.tsx
  src/app/api/ai/interview/route.ts
  src/constants/interview-constants.ts
  src/features/interview/camera-view.tsx
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/interview/hooks/use-timer.ts
  src/features/interview/question-display.tsx
  src/features/interview/question-step.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/interview/timer.tsx
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form.tsx
  src/features/resume/user-info-summary.tsx
  src/store/use-interview-store.ts
Labels: 🎨 Styles, 🚨 ASAP, ☕️민조

#126 Bugfix/#125 my page bug
  src/features/interview-history/interview-history-list.tsx
  src/features/user-meta-data/data/user-meta-data.ts
  src/features/user-meta-data/select-box.tsx
Labels: 🐞 BugFix, 🚨 ASAP, 💎다혜

#124 Bugfix:#123 metadata 오류 해결
  src/app/(with-nav)/(with-header)/resume/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/features/resume/user-info-summary.tsx
Labels: 🐞 BugFix, ☕️민조

#119 style:#118-user-meta-data ui구현
  src/features/user-meta-data/select-box.tsx
  src/features/user-meta-data/single-select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
Labels: 🎨 Styles, 💎다혜

#117 Refactor/#102 null 데이터 페이지
  src/components/common/resume-card.tsx
  src/features/interview/resume-cards-box.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/job/job-postings-box.tsx
Labels: 🔨 Refactor, 🎨 Styles, 🚨 ASAP, ♟️창연

#127 Hotfix/#122 유저 메타데이터 오류
  src/app/api/job/posting/route.ts
  src/features/job/api/server-services.ts
  src/features/job/job-postings-box.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 🚨 ASAP

#128 Feature/#116 mypage interview detail
  src/app/api/ai/interview/route.ts
  src/constants/interview-constants.ts
  src/features/character/header-character-card.tsx
  src/features/character/my-character.tsx
  src/features/character/my-page-character-card.tsx
  src/features/my-page/interview-detail-field.tsx
  src/features/my-page/my-info.tsx
  src/features/my-page/viewing-field.tsx
Labels: ✨ Feature, 🕶️ 재원

#130 Bugfix/#129 user meta data bug
  src/app/api/regions/route.ts
  src/components/icons/file-dock-search-fill.tsx
  src/components/icons/interview-icon.tsx
  src/components/icons/job-icon.tsx
  src/components/icons/logout-icon.tsx
  src/components/icons/my-page-icon.tsx
  src/components/icons/resume-icon.tsx
  src/components/icons/sign-in-icon.tsx
  src/components/icons/sign-up-icon.tsx
  src/features/layout/nav.tsx
Labels: 🐞 BugFix, 🚨 ASAP, 💎다혜

#133 Hotfix/#132 배포 페이지 수정
  src/components/common/error-component.tsx
  src/components/common/resume-card.tsx
  src/features/interview/question-display.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/interview/timer.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/job-postings-box.tsx
  src/features/my-page/my-info.tsx
  src/features/resume/user-info-summary.tsx
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/features/user-meta-data/hooks/use-meta-data-query.ts
Labels: 🐞 BugFix, 🚨 ASAP

#138 Style/#135 nav style
  public/assets/character/card/card_assets.svg
  src/components/icons/chat-alt-2-fill.tsx
  src/components/icons/chick-logo.tsx
  src/components/icons/interview-full-icon.tsx
  src/components/icons/interview-icon.tsx
  src/components/icons/job-full-icon.tsx
  src/components/icons/job-icon.tsx
  src/components/icons/logout-icon.tsx
  src/components/icons/my-page-full-icon.tsx
  src/components/icons/my-page-icon.tsx
  src/components/icons/resume-full-icon.tsx
  src/components/icons/resume-icon.tsx
  src/components/icons/sign-in-icon.tsx
  src/components/icons/sign-up-icon.tsx
  src/components/icons/trash.tsx
  src/features/layout/data/nav-items.tsx
  src/features/layout/link-nav.tsx
  src/features/layout/nav.tsx
  src/features/resume/user-info-summary.tsx
Labels: 🎨 Styles, 🕶️ 재원, ☕️민조

#141 Feature/#137 badge component
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/styles/badge-styles.ts
  src/styles/button-styles.ts
Labels: ✨ Feature, 🎨 Styles, 💎다혜

#148 Refactor/#140 sign optimization
  src/app/auth/sign-in/page.tsx
  src/app/auth/sign-up/page.tsx
  src/app/global-error.tsx
  src/constants/message-constants.ts
  src/features/sign/auth-input.tsx
  src/features/sign/hooks/use-sign-in-result.ts
  src/features/sign/sign-in-auth-form.tsx
  src/features/sign/sign-up-auth-form.tsx
Labels: 🔨 Refactor, 🎨 Styles, 🕶️ 재원

#150 Refactor/#121 ai interivew
  src/app/(with-nav)/(with-header)/interview/live/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/app/api/ai/interview/route.ts
  src/app/api/resume/[id]/route.ts
  src/app/api/resume/draft/[id]/route.ts
  src/app/api/resume/draft/route.ts
  src/app/api/resume/route.ts
  src/constants/interview-constants.ts
  src/constants/message-constants.ts
  src/features/interview-history/interview-history-list.tsx
  src/features/interview/api/client-services.ts
  src/features/interview/camera-view.tsx
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/interview/hooks/use-camera-stream.ts
  src/features/interview/hooks/use-webcam-stream.ts
  src/features/interview/question-display-with-timer.tsx
  src/features/interview/question-display.tsx
  src/features/interview/timer.tsx
Labels: 🔨 Refactor, ☕️민조

#154 Feature/#152 add character type
  public/assets/character/card/clay-level1.png
  public/assets/character/card/clay-level2.png
  public/assets/character/card/clay-level3.png
  public/assets/character/card/clay-level4.png
  public/assets/character/card/clay-level5.png
  public/assets/character/card/clay-level6.png
  public/assets/character/card/poly-level1.png
  public/assets/character/card/poly-level2.png
  public/assets/character/card/poly-level3.png
  public/assets/character/card/poly-level4.png
  public/assets/character/card/poly-level5.png
  public/assets/character/card/poly-level6.png
  public/assets/character/header/clay-level1.png
  public/assets/character/header/clay-level2.png
  public/assets/character/header/clay-level3.png
  public/assets/character/header/clay-level4.png
  public/assets/character/header/clay-level5.png
  public/assets/character/header/clay-level6.png
  public/assets/character/header/poly-level1.png
  public/assets/character/header/poly-level2.png
  public/assets/character/header/poly-level3.png
  public/assets/character/header/poly-level4.png
  public/assets/character/header/poly-level5.png
  public/assets/character/header/poly-level6.png
  public/assets/character/interviewer/clay-Interviewer-calm.png
  public/assets/character/interviewer/clay-Interviewer-pressure.png
  public/assets/character/interviewer/poly-Interviewer-calm.png
  public/assets/character/interviewer/poly-Interviewer-pressure.png
  src/components/icons/left-arrow-icon.tsx
  src/components/icons/right-arrow-icon.tsx
  src/constants/character-constants.ts
  src/features/character/character-detail-modal.tsx
  src/features/character/character-history.tsx
  src/features/character/create-character-modal.tsx
  src/features/character/data/character-data.ts
  src/features/character/header-character-card.tsx
  src/features/character/my-character.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/layout/utils/getTitleFromPath.ts
Labels: 🔨 Refactor, 🎨 Styles, 🕶️ 재원

#151 Feature/#146 마이페이지 채용공고
  src/app/api/job/bookmark/route.ts
  src/components/icons/star.tsx
  src/constants/message-constants.ts
  src/constants/time-constants.ts
  src/features/bookmark-selected/api/client-services.ts
  src/features/bookmark-selected/bookmark-selected-list.tsx
  src/features/bookmark-selected/bookmark-tab.tsx
  src/features/bookmark-selected/hook/use-bookmark-selected-infinite-query.ts
  src/features/interview-history/empty-interview-list.tsx
  src/features/interview-history/interview-history-list.tsx
  src/features/interview/resume-card.tsx
  src/features/interview/resume-cards-box.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/job-posting-card.tsx
  src/features/job/job-postings-box.tsx
  src/features/my-page/empty-list.tsx
  src/features/my-page/list-by-tab.tsx
  src/features/my-page/tab-buttons.tsx
  src/utils/format-remain-day.ts
Labels: 📬 API, ✨ Feature, 🚨 ASAP, ♟️창연

#153 Feature/#149 character level up flow
  src/app/(with-nav)/(with-header)/character/page.tsx
  src/app/api/character/experience/route.ts
  src/app/api/resume/count/route.ts
  src/constants/character-constants.ts
  src/constants/message-constants.ts
  src/features/character/create-character-modal.tsx
  src/features/character/data/character-data.ts
  src/features/character/hooks/use-character-card.ts
  src/features/character/hooks/use-experience-up.ts
  src/features/character/utils/get-level-and-percent.ts
  src/features/character/utils/get-level-and-percentage.ts
  src/features/interview/timer.tsx
  src/features/resume/api/client-services.ts
  src/features/resume/hooks/use-resume-form.ts
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
Labels: ✨ Feature, 🔨 Refactor, 💎다혜

#155 Refactor/#147 modal component
  src/app/layout.tsx
  src/components/icons/close.tsx
  src/components/ui/modal.tsx
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/resume/draft-resume-item.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form-action-button.tsx
  src/features/resume/resume-form.tsx
Labels: 🔨 Refactor, 🎨 Styles, ☕️민조

#157 Refactor/#143 button component disabled
  src/app/page.tsx
  src/components/ui/button.tsx
  src/styles/button-styles.ts
Labels: 🎨 Styles, 💎다혜

#164 Style/#161 user meta form UI
  src/components/ui/modal.tsx
  src/constants/character-constants.ts
  src/features/user-meta-data/select-box.tsx
  src/features/user-meta-data/single-select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
Labels: 🎨 Styles, 💎다혜

#170 Refactor/#159 ai interview
  src/app/(with-nav)/(with-header)/interview/live/[id]/page.tsx
  src/app/api/ai/feedback/route.ts
  src/app/api/ai/interview/[id]/route.ts
  src/app/api/ai/interview/route.ts
  src/app/api/ai/route.ts
  src/app/api/ai/stt/route.ts
  src/app/api/ai/tts/route.ts
  src/constants/interview-constants.ts
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/interview/api/client-services.ts
  src/features/interview/api/server-services.ts
  src/features/interview/hooks/use-ai-feedback-mutation.ts
  src/features/interview/hooks/use-audio-recorder.ts
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/interview/hooks/use-interview-history-mutation.ts
  src/features/interview/question-display-with-timer.tsx
  src/features/interview/question-display.tsx
  src/features/interview/question-step.tsx
  src/features/interview/timer.tsx
  src/features/interview/utils/handle-voice-to-ai-flow.ts
  src/lib/open-ai.ts
  src/types/interview.ts
  src/types/message.ts
Labels: 📬 API, 🔨 Refactor, ☕️민조

#167 Bugfix/#160 interview history feedback status
  src/app/(with-nav)/(with-header)/my-page/page.tsx
  src/app/api/interview-history/[userId]/route.ts
  src/components/ui/loading-spinner.tsx
  src/features/interview-history/api/client-services.ts
  src/features/interview-history/interview-history-list.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
Labels: 🔨 Refactor, 💎다혜

#166 Refactor/#162 북마크 필터링 수정
  prisma/schema.prisma
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/api/job/posting/route.ts
  src/constants/education-constants.ts
  src/features/bookmark-selected/api/client-services.ts
  src/features/bookmark-selected/bookmark-tab.tsx
  src/features/job/api/client-services.ts
  src/features/job/api/server-services.ts
  src/features/job/bookmark.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/hooks/use-bookmark-query.ts
  src/features/job/hooks/use-job-posting-query.ts
  src/features/job/job-posting-card.tsx
  src/features/job/job-postings-box.tsx
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/utils/format-remain-day.ts
  src/utils/format-timestamp.ts
Labels: 🔨 Refactor, 🚨 ASAP, ♟️창연

#177 Hotfix/#176 image name
  public/assets/character/interviewer/clay-interviewer-calm.png
  public/assets/character/interviewer/clay-interviewer-pressure.png
  public/assets/character/interviewer/poly-interviewer-calm.png
  public/assets/character/interviewer/poly-interviewer-pressure.png
Labels: 🕶️ 재원, 🚨 ASAP

#180 Hotfix/#179-사람인-출처
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/constants/interview-constants.ts
Labels: 🚨 ASAP, ♟️창연

#184 Feature/#182 redirect after login
  src/features/character/my-character.tsx
  src/features/sign/hooks/use-sign-in-result.ts
  src/features/sign/sign-in-auth-form.tsx
  src/middleware.ts
  src/utils/auth-option.ts
Labels: ✨ Feature, 🕶️ 재원

#185 Refactor/#183 북마크 상태관리
  prisma/schema.prisma
  src/app/api/sample/[id]/route.ts
  src/app/sample/[id]/page.tsx
  src/constants/sample-constant.ts
  src/constants/time-constants.ts
  src/features/job/bookmark.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/job-posting-card.tsx
  src/features/job/job-postings-box.tsx
  src/features/sample/api/client-services.ts
  src/features/sample/api/server-services.ts
  src/features/sample/client-component.tsx
  src/features/sample/hooks/use-sample-hook.ts
  src/features/sample/hooks/use-sample-mutation.ts
  src/features/sample/hooks/use-sample-query.ts
  src/features/sample/sample-component.tsx
  src/store/sample-store.ts
  src/types/DTO/.gitkeep
  src/types/DTO/character-dto.ts
  src/types/DTO/character-history-dto.ts
  src/types/DTO/interview-history-dto.ts
  src/types/DTO/interview-qna-dto.ts
  src/types/DTO/job-posting-dto.ts
  src/types/DTO/jobs-dto.ts
  src/types/DTO/main-region-dto.ts
  src/types/DTO/resume-dto.ts
  src/types/DTO/sub-region-dto.ts
  src/types/DTO/user-dto.ts
  src/types/DTO/user-selected-job-dto.ts
  src/types/sample.ts
Labels: 🔨 Refactor, 🚨 ASAP, ♟️창연

#187 Bugfix/#172 button tab counting
  src/app/api/interview-history/[userId]/route.ts
  src/app/api/my-page/tab-counts/[userId]/route.ts
  src/constants/message-constants.ts
  src/constants/my-page-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/bookmark-selected/bookmark-tab.tsx
  src/features/interview-history/hook/use-delete-interview-mutation.ts
  src/features/interview-history/interview-detail-feedback.tsx
  src/features/interview-history/interview-detail-field.tsx
  src/features/interview/timer.tsx
  src/features/job/bookmark.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/my-page/api/client-services.ts
  src/features/my-page/hook/use-tab-count-query.ts
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/user-meta-data/hooks/use-meta-data-form.ts
Labels: 🐞 BugFix, 🔨 Refactor, 💎다혜

#186 Style/#156 resume
  src/app/(with-nav)/(with-header)/resume/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/constants/message-constants.ts
  src/constants/query-key.ts
  src/features/interview-history/hook/use-delete-interview-mutation.ts
  src/features/interview-history/interview-detail-field.tsx
  src/features/my-page/list-by-tab.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/my-page/viewing-field.tsx
  src/features/resume-list/hooks/use-resume-list-query.ts
  src/features/resume-list/hooks/use-resume-query.ts
  src/features/resume-list/resume-detail-field.tsx
  src/features/resume-list/resume-item.tsx
  src/features/resume-list/resume-list.tsx
  src/features/resume-list/resume-qna-item.tsx
  src/features/resume/api/client-services.ts
  src/features/resume/draft-resume-item.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/hooks/use-add-resume-mutation.ts
  src/features/resume/hooks/use-delete-resume-mutation.ts
  src/features/resume/hooks/use-draft-resume-list-query.ts
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form-action-button.tsx
  src/features/resume/resume-form.tsx
  src/features/resume/user-data-item.tsx
  src/features/resume/user-info-summary.tsx
Labels: 🔨 Refactor, 🎨 Styles, ☕️민조

#193 bugfix:#191 마이페이지 > 내가 작성한 자소서 삭제 시 tab count 반영되도록 수정
  src/app/api/my-page/tab-counts/[userId]/route.ts
  src/app/global-style.css
  src/constants/path-constant.ts
  src/features/layout/button-nav.tsx
  src/features/layout/data/nav-items.tsx
  src/features/layout/nav.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/resume/hooks/use-delete-resume-mutation.ts
  src/middleware.ts
Labels: 🐞 BugFix, 💎다혜

#197 Feature/#188 면접 이어하기
  src/app/(with-nav)/(with-header)/interview/live/[id]/page.tsx
  src/app/api/ai/interview/[id]/route.ts
  src/constants/interview-constants.ts
  src/features/interview/api/client-services.ts
  src/features/interview/api/server-services.ts
  src/features/interview/hooks/use-interview-history-mutation.ts
  src/features/interview/interview-client.tsx
  src/features/interview/question-display-with-timer.tsx
  src/features/interview/question-display.tsx
  src/features/interview/timer.tsx
  src/store/use-interview-store.ts
Labels: ✨ Feature, ♟️창연

#198 Style/#190 alert
  package.json
  pnpm-lock.yaml
  src/app/global-style.css
  src/app/layout.tsx
  src/components/ui/modal.tsx
  src/constants/message-constants.ts
  src/constants/notiflix-constants.ts
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/hooks/use-resume-form.ts
  src/provider/notiflix-provider.tsx
  src/styles/notiflix-styles.ts
  src/utils/show-notiflix-confirm.ts
Labels: 🎨 Styles, ☕️민조

#199 Refactor/#189 job posting
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/api/job/posting/route.ts
  src/constants/message-constants.ts
  src/features/job/api/client-services.ts
  src/features/job/api/server-services.ts
  src/features/job/bookmark.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/hooks/use-job-posting-query.ts
  src/features/job/job-posting-block-component.tsx
  src/features/job/job-posting-card.tsx
  src/features/job/job-posting-pagination-button.tsx
  src/features/job/job-posting-section.tsx
  src/features/job/job-posting-select-box.tsx
  src/features/job/job-postings-box.tsx
Labels: ✨ Feature, 🔨 Refactor, 🕶️ 재원

#203 Hotfix/#202 interview status
  src/features/interview/interview-client.tsx
  src/features/interview/question-display-with-timer.tsx
  src/features/interview/question-display.tsx
Labels: 🐞 BugFix, 🚨 ASAP, ♟️창연

#195 style:#194 전체 스타일 적용 및 중복 main 태그 제거
  src/app/(with-nav)/(with-header)/interview/start/page.tsx
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/components/common/block-component.tsx
  src/components/ui/modal.tsx
  src/components/ui/screen-overlay.tsx
  src/features/interview-history/interview-detail-history.tsx
  src/features/interview/interview-client.tsx
  src/features/job/job-posting-block-component.tsx
  src/features/job/job-posting-pagination-button.tsx
  src/features/job/job-posting-section.tsx
  src/features/job/job-postings-box.tsx
  src/features/layout/header.tsx
  src/features/layout/nav.tsx
  src/features/resume/resume-form-action-button.tsx
  tailwind.config.ts
Labels: 🎨 Styles, 💎다혜

#204 Feature/#173 history feedback
  public/assets/character/interviewer/clay-interviewer-icon-calm.png
  public/assets/character/interviewer/clay-interviewer-icon-pressure.png
  public/assets/character/interviewer/poly-interviewer-icon-calm.png
  public/assets/character/interviewer/poly-interviewer-icon-pressure.png
  src/app/api/interview-history/[userId]/route.ts
  src/app/api/job/bookmark/route.ts
  src/app/api/my-page/tab-counts/[userId]/route.ts
  src/app/api/user-meta-data/[userId]/route.ts
  src/constants/interview-constants.ts
  src/features/bookmark-selected/bookmark-selected-list.tsx
  src/features/bookmark-selected/bookmark-tab.tsx
  src/features/bookmark-selected/hook/use-bookmark-selected-infinite-query.ts
  src/features/interview-history/api/client-services.ts
  src/features/interview-history/hook/use-delete-interview-mutation.ts
  src/features/interview-history/hook/use-get-interview-detail-query.ts
  src/features/interview-history/hook/use-interview-history-infinite-query.ts
  src/features/interview-history/interview-detail-feedback.tsx
  src/features/interview-history/interview-detail-field.tsx
  src/features/interview-history/interview-detail-history.tsx
  src/features/interview-history/interview-history-list.tsx
  src/features/interview/resume-card.tsx
  src/features/interview/timer.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/my-page/viewing-field.tsx
  src/features/resume-list/hooks/use-resume-list-query.ts
  src/features/resume-list/hooks/use-resume-query.ts
  src/features/resume-list/resume-detail-field.tsx
  src/features/resume-list/resume-item.tsx
  src/features/resume-list/resume-list.tsx
  src/features/user-meta-data/api/client-services.ts
  src/features/user-meta-data/api/server-services.ts
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/features/user-meta-data/hooks/use-meta-data-mutation.ts
  src/features/user-meta-data/hooks/use-meta-data-query.ts
  src/features/user-meta-data/single-select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
Labels: 🔨 Refactor, 🎨 Styles, 💎다혜

#207 Refactor/#206 confirm
  src/constants/notiflix-constants.ts
  src/styles/notiflix-styles.ts
  src/utils/show-notiflix-confirm.ts
Labels: 🔨 Refactor, 🚨 ASAP, ☕️민조

#209 style:#208 카드 css 수정
  src/components/ui/card.tsx
  src/features/job/job-posting-card.tsx
  src/features/job/job-postings-box.tsx
Labels: 🎨 Styles, 🚨 ASAP, 💎다혜

#215 Style/#214 confirm
  src/styles/notiflix-styles.ts
  tailwind.config.ts
Labels: 🎨 Styles, 🚨 ASAP, ☕️민조

#212 Refactor/#200 auth
  src/app/api/auth/sign-in/route.ts
  src/app/api/sign-up/route.ts
  src/components/icons/eye-icon.tsx
  src/components/icons/eye-off-icon.tsx
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/features/character/hooks/use-character-card.ts
  src/features/job/job-posting-block-component.tsx
  src/features/sign/auth-input.tsx
  src/features/sign/data/sign-input.ts
  src/features/sign/data/sign-up-schema.ts
  src/features/sign/hooks/use-sign-in-result.ts
  src/features/sign/sign-in-auth-form.tsx
  src/features/sign/sign-up-auth-form.tsx
  src/middleware.ts
  src/utils/auth-option.ts
  tailwind.config.ts
Labels: 🔨 Refactor, 🎨 Styles, ☕️민조

#213 Refactor/#205 resume
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/app/api/resume/count/route.ts
  src/constants/message-constants.ts
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/hooks/use-add-resume-mutation.ts
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form-action-button.tsx
  src/features/resume/resume-form.tsx
Labels: 🔨 Refactor, 🕶️ 재원

#218 Style/#217 nav
  src/app/(with-nav)/auth/sign-in/page.tsx
  src/app/(with-nav)/auth/sign-up/page.tsx
  src/app/auth/sign-up/character/page.tsx
  src/features/layout/button-nav.tsx
  src/features/layout/data/nav-items.tsx
  src/features/layout/link-nav.tsx
  src/features/layout/nav.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Styles, 🕶️ 재원

#219 Bugfix/#216 maintain tab button
  src/app/api/my-page/tab-counts/[userId]/route.ts
  src/constants/my-page-constants.ts
  src/features/bookmark-selected/bookmark-selected-list.tsx
  src/features/interview-history/interview-history-list.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/my-page/empty-list.tsx
  src/features/my-page/list-by-tab.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/my-page/utils/get-my-page-path.ts
  src/features/my-page/viewing-field.tsx
  src/features/resume-list/resume-detail-field.tsx
  src/features/resume-list/resume-list.tsx
  src/features/resume/api/client-services.ts
  src/features/resume/hooks/use-add-resume-mutation.ts
  src/features/resume/hooks/use-delete-resume-mutation.ts
  src/features/resume/hooks/use-resume-form.ts
  src/store/use-tab-store.ts
  src/types/tab-type.ts
Labels: 🐞 BugFix, 🔨 Refactor, 💎다혜

#222 Refactor/#200 auth
  src/constants/message-constants.ts
  src/features/sign/auth-input.tsx
  src/features/sign/hooks/use-sign-in-result.ts
  src/features/sign/sign-in-auth-form.tsx
Labels: 🔨 Refactor, ☕️민조

#226 Style/#223 notiflix notify color
  src/styles/notiflix-styles.ts
Labels: 🎨 Styles, 🚨 ASAP, ☕️민조

#211 Feature/#188 interview continue UI
  src/app/(with-nav)/(with-header)/interview/live/[id]/page.tsx
  src/app/(with-nav)/(with-header)/interview/start/page.tsx
  src/app/api/ai/interview/[id]/route.ts
  src/app/api/interview-history/[userId]/route.ts
  src/components/icons/block-camera.tsx
  src/components/icons/using-camera.tsx
  src/constants/notiflix-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/interview/alert-in-progress.tsx
  src/features/interview/api/client-services.ts
  src/features/interview/api/server-services.ts
  src/features/interview/camera-view.tsx
  src/features/interview/hooks/use-audio-with-timer.ts
  src/features/interview/hooks/use-in-progress-mutation.ts
  src/features/interview/hooks/use-in-progress-query.ts
  src/features/interview/hooks/use-interview-history-mutation.ts
  src/features/interview/interview-block-component.tsx
  src/features/interview/interview-client.tsx
  src/features/interview/question-display-with-timer.tsx
  src/features/interview/question-display.tsx
  src/features/interview/resume-cards-box.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/interview/timer.tsx
  src/store/use-interview-store.ts
Labels: ✨ Feature, 🎨 Styles, ♟️창연

#230 Refactor/#228 button component UI refactoring
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/favicon.ico
  src/app/global-style.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/block-component.tsx
  src/components/ui/button.tsx
  src/components/ui/link-button.tsx
  src/features/bookmark-selected/bookmark-tab.tsx
  src/features/character/create-character-modal.tsx
  src/features/interview-history/interview-detail-feedback.tsx
  src/features/interview-history/interview-detail-field.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/interview/timer.tsx
  src/features/job/job-posting-card.tsx
  src/features/resume-list/resume-detail-field.tsx
  src/features/resume/hooks/use-resume-form.ts
  src/features/resume/resume-form-action-button.tsx
  src/features/resume/resume-form.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/styles/button-styles.ts
Labels: 🔨 Refactor, 🎨 Styles, 💎다혜

#232 Refactor/#201 modal component
  public/assets/visual_assets.png
  src/components/ui/modal.tsx
  src/components/ui/typography.tsx
  src/features/character/character-detail-modal.tsx
  src/features/character/character-history.tsx
  src/features/character/main-character-card.tsx
  src/features/character/my-character.tsx
  src/features/on-boarding/list-card.tsx
  src/hooks/customs/use-infinite-scroll.ts
  src/utils/show-notiflix-confirm.ts
  tailwind.config.ts
Labels: 🔨 Refactor, 🎨 Styles, ☕️민조

#229 Refactor/#196 meta data history list refactoring
  src/app/(with-nav)/(with-header)/my-page/page.tsx
  src/app/api/ai/interview/[id]/route.ts
  src/app/api/regions/route.ts
  src/components/common/error-component.tsx
  src/components/icons/improvement-icon.tsx
  src/components/icons/strength-icon.tsx
  src/components/ui/button.tsx
  src/components/ui/select-box.tsx
  src/components/ui/typography.tsx
  src/constants/message-constants.ts
  src/constants/path-constant.ts
  src/constants/query-key.ts
  src/features/character/main-character-card.tsx
  src/features/character/my-page-character-card.tsx
  src/features/interview-history/hook/use-delete-interview-mutation.ts
  src/features/interview-history/hook/use-get-interview-detail-query.ts
  src/features/interview-history/hook/use-intersection-observer-hook.ts
  src/features/interview-history/interview-detail-feedback.tsx
  src/features/interview-history/interview-detail-field.tsx
  src/features/interview-history/interview-detail-history.tsx
  src/features/interview-history/interview-history-list.tsx
  src/features/interview-history/utils/get-interviewer-name.ts
  src/features/interview/hooks/use-camera-stream.ts
  src/features/interview/utils/handle-voice-to-ai-flow.ts
  src/features/layout/header-title.tsx
  src/features/my-page/api/client-services.ts
  src/features/my-page/my-info-content.tsx
  src/features/my-page/my-info.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/my-page/utils/get-my-page-path.ts
  src/features/my-page/viewing-field.tsx
  src/features/on-boarding/list-card.tsx
  src/features/resume/hooks/use-resume-form.ts
  src/features/sign/sign-up-auth-form.tsx
  src/features/user-meta-data/api/client-services.ts
  src/features/user-meta-data/data/user-meta-data.ts
  src/features/user-meta-data/data/user-meta-form-schema.ts
  src/features/user-meta-data/hooks/use-meta-data-form.ts
  src/features/user-meta-data/hooks/use-regions-query.ts
  src/features/user-meta-data/select-field.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/hooks/customs/use-func-debounce.ts
  src/types/user-meta-data-type.ts
  src/utils/get-error-message.ts
Labels: 🔨 Refactor, 🎨 Styles, 💎다혜

#236 Refactor/#224 job posting
  prisma/schema.prisma
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/api/job/posting/route.ts
  src/components/ui/card.tsx
  src/features/job/hooks/use-bookmark-mutation.ts
  src/features/job/job-posting-card.tsx
  src/features/job/job-posting-section.tsx
  src/features/job/job-postings-box.tsx
  src/types/DTO/main-region-dto.ts
  src/types/DTO/sub-region-dto.ts
  tailwind.config.ts
Labels: 🔨 Refactor, 🕶️ 재원, 🗄️ db

#243 Style#241 responsive header nav
  src/app/page.tsx
  src/components/ui/badge.tsx
  src/features/character/header-character-card.tsx
  src/features/layout/data/nav-items.tsx
  src/features/layout/header-title.tsx
  src/features/layout/header.tsx
  src/features/layout/nav.tsx
Labels: 🎨 Styles, 🚨 ASAP, 💎다혜

#244 style:#241-responsive-header-nav-2
  src/components/ui/modal.tsx
  src/features/character/header-character-card.tsx
  src/features/layout/nav.tsx
  tailwind.config.ts
Labels: 🎨 Styles, 🚨 ASAP, 💎다혜

#242 Style/#239 자소서 반응형
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/(with-nav)/(with-header)/resume/[id]/page.tsx
  src/app/(with-nav)/(with-header)/resume/page.tsx
  src/components/icons/trash.tsx
  src/features/resume/draft-resume-item.tsx
  src/features/resume/draft-resumes-modal.tsx
  src/features/resume/question-answer-field.tsx
  src/features/resume/resume-form-action-button.tsx
  src/features/resume/resume-form.tsx
  tailwind.config.ts
Labels: 🎨 Styles, 🚨 ASAP, ♟️창연

#246 Style:#243 on-boarding page tablet,mobile 반응형 추가
  public/assets/tablet_chickchick.png
  src/app/(with-nav)/on-boarding/page.tsx
  src/app/global-style.css
  src/app/page.tsx
  src/features/character/main-character-card.tsx
  src/features/home/desktop-home.tsx
  src/features/home/mobile-home.tsx
  src/features/home/render-home.tsx
  src/features/home/tablet-home.tsx
  src/features/layout/back-button.tsx
  src/features/layout/header.tsx
  src/features/on-boarding/list-card.tsx
  src/hooks/customs/use-device-type.ts
Labels: 🎨 Styles, 💎다혜

#247 Style#235 responsive my page
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/(with-nav)/(with-header)/my-page/page.tsx
  src/features/bookmark-selected/bookmark-tab.tsx
  src/features/character/character-detail-modal.tsx
  src/features/character/my-page-character-card.tsx
  src/features/my-page/my-info-content.tsx
  src/features/my-page/my-info.tsx
  src/features/my-page/tab-buttons.tsx
  src/features/my-page/tabs-field.tsx
  src/features/my-page/viewing-field.tsx
  src/features/resume-list/resume-detail-field.tsx
  src/features/resume-list/resume-item.tsx
  src/features/resume-list/resume-list.tsx
  src/features/user-meta-data/user-meta-data-form.tsx
  src/features/user-meta-data/user-meta-data-modal.tsx
Labels: 🎨 Styles, 💎다혜

#255 Hotfix/#254 면접 페이지 오류
  src/app/(with-nav)/(with-header)/interview/start/page.tsx
  src/features/interview/select-interviewer-box.tsx
Labels: 🐞 BugFix, 🚨 ASAP, ♟️창연

#261 Hotfix/#259 lottie error
  src/components/common/loading-animation.tsx
  src/components/common/lottie-animation.tsx
  src/types/interview.ts
  src/types/job-posting.ts
  src/types/user.ts
Labels: 🐞 BugFix, 🚨 ASAP, ♟️창연

#262 bugfix:#260 컴포넌트가 마운트된 이후에 렌더링하도록 설정
  src/features/home/render-home.tsx
Labels: 🐞 BugFix, 🚨 ASAP, 💎다혜

#251 Style#248 responsive job posting
  src/app/(with-nav)/(with-header)/job/page.tsx
  src/app/(with-nav)/(with-header)/layout.tsx
  src/app/global-style.css
  src/features/job/job-posting-card.tsx
  src/features/job/job-posting-select-box.tsx
  src/features/job/job-postings-box.tsx
  src/features/job/saramin-button.tsx
Labels: 🎨 Styles, 💎다혜

#257 Style/#253 404 page
  public/assets/notfound.png
  src/app/not-found.tsx
  src/components/common/block-component.tsx
Labels: ✨ Feature, 🎨 Styles, ♟️창연

#265 Hotfix/#264 resume list status error
  src/app/api/resume/route.ts
  src/features/interview/resume-all-modal.tsx
  src/features/interview/resume-cards-box.tsx
  src/features/my-page/empty-list.tsx
  src/features/resume-list/resume-item.tsx
  src/features/resume-list/resume-list.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 🚨 ASAP, 💎다혜

#268 style:#236 mobile에서 nav에 home 버튼도 노출되도록 추가
  src/features/layout/data/nav-items.tsx
Labels: 🎨 Styles, 🚨 ASAP, 💎다혜

#269 Hotfix/#267 mobile UI
  src/features/bookmark-selected/bookmark-selected-list.tsx
  src/features/character/character-detail-modal.tsx
  src/features/interview-history/interview-history-list.tsx
  src/features/interview/select-interviewer-box.tsx
  src/features/job/job-postings-box.tsx
  src/features/resume-list/resume-list.tsx
  src/lottie/pressure.json
Labels: 🐞 BugFix, 🚨 ASAP
